# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField(max_length=5)),
                ('city_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.Location')),
            ],
        ),
    ]
